#!/usr/bin/env python3

import sys, os

argc = len(sys.argv)

usage = '''USAGE:
%s 'remote' 'local_branch' 'commit_arg_1' 'commit_arg_2' ...

\tremote: the remote on which you want to push data.
\tlocal_branch: your branch you want to push news onto.
\tcommit_arg_X: corresponds to a '-m' flag of 'git commit'.'''

#Check for a correct amount of arguments.
if argc < 3:
    print(usage % (sys.argv[0] if (sys.argv and sys.argv[0]) else './push_that'))
    print('\nError tracked: Lack of argument(s), minimum: 3.')
    sys.exit(1)

commit_args = ''

#Puts all of the commit arguments into 'commit_args'.
for arg in sys.argv[3:]:
    contain_space = ' ' in arg
    commit_args += '-m ' + ("'" + arg + "'" if contain_space else arg) + ' '
commit_args = commit_args[:-1]

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

if os.system('git add --all') != 0:
    print("%s[1/3] - %sAn unexpected error occured when adding modified files through 'git add --all'.%s"
            % (bcolors.ENDC, bcolors.FAIL, bcolors.ENDC))
    sys.exit(1)
else:
    print("%s[1/3] - %sAdded all of the non-ignored files to git.%s"
            % (bcolors.ENDC, bcolors.OKGREEN, bcolors.ENDC))

if os.system('git commit ' + commit_args) != 0:
    print("%s[2/3] - %sAn unexpected error occured when adding modified files through 'git commit %s'.%s"
            % (bcolors.ENDC, bcolors.FAIL, commit_args, bcolors.ENDC))
    sys.exit(1)
else:
    print('%s[2/3] - %sSuccessfully Committed.%s'
            % (bcolors.ENDC, bcolors.OKGREEN, bcolors.ENDC))

if os.system('git push ' + sys.argv[1] + ' ' + sys.argv[2]) != 0:
    print("%s[3/3] - %sAn unexpected error occured when adding modified files through 'git push %s'.%s"
            % (bcolors.ENDC, bcolors.FAIL, sys.argv[1] + ' ' + sys.argv[2], bcolors.ENDC))
    sys.exit(1)
else:
    print("%s[3/3] - %sPushed data to %s from %s.%s"
            % (bcolors.ENDC, bcolors.OKGREEN, sys.argv[1], sys.argv[2], bcolors.ENDC))

sys.exit(0)
